//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PennyMovieWeb.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TWMovieList
    {
        public string MovieID { get; set; }
        public string MovieType { get; set; }
        public Nullable<int> PublishYear { get; set; }
        public string ImgName { get; set; }
        public string ImgURL { get; set; }
        public string Summary { get; set; }
        public string Director { get; set; }
        public string MovieName { get; set; }
        public string Trailer { get; set; }
    }
}
